kind: Service
apiVersion: v1
metadata:
  name: open-match-evaluator
  namespace: open-match
  labels:
    app: open-match-customize
    component: evaluator
    release: open-match
spec:
  selector:
    app: open-match-customize
    component: evaluator
    release: open-match
  clusterIP: None
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 50508
    - name: http
      protocol: TCP
      port: 51508
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: om-evaluator
  namespace: open-match
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: om-evaluator
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-evaluator
  namespace: open-match
  labels:
    app: open-match-customize
    component: evaluator
    release: open-match
spec:
  replicas: 3
  selector:
    matchLabels:
      app: open-match-customize
      component: evaluator
  template:
    metadata:
      namespace: open-match
      labels:
        app: open-match-customize
        component: evaluator
        release: open-match
    spec:
      containers:
        - name: om-evaluator
          image: registry.cn-hangzhou.aliyuncs.com/ringtail/openmatch-default-evaluator:1.7.0
          ports:
            - name: grpc
              containerPort: 50508
            - name: http
              containerPort: 51508
          volumeMounts:
          - name: om-config-volume-override
            mountPath: /app/config/override
          - name: om-config-volume-default
            mountPath: /app/config/default
      volumes:
      - name: om-config-volume-override
        configMap:
          name: open-match-configmap-override
      - name: om-config-volume-default
        configMap:
          name: open-match-configmap-default